
---
# deploy

- name: deploy
  hosts: deploy
  gather_facts: no
  tasks:
    - name: default user
      user: name=comments
            system=yes
            createhome=no
            groups=webstack
      sudo: true
      when: target_user == 'comments'
    
    - name: custom user
      user: name={{target_user}}
      sudo: true
      when: target_user != 'comments'
    
    - name: data dirs
      file: path={{item}} owner={{target_user}} group=webstack state=directory mode=0775
      with_items:
        - /data/deploy/comments/main
        - /data/deploy/comments/prev
        - /data/deploy/comments/next
      sudo: true
      when: not assets_only
    
    - name: project dirs
      file: path={{item}} owner={{target_user}} group=webstack state=directory mode=0775
      with_items:
        - /home/deploy/backups/comments
        - /home/deploy/projects/comments
        - /home/deploy/projects/comments/target
        - /home/deploy/projects/comments/target/data
        - /home/deploy/projects/comments/{{deploy_rev_prefix}}
      sudo: true
    
    - name: link data main
      file: src=/data/deploy/comments/main
            dest=/home/deploy/projects/comments/target/data/main
            owner={{target_user}}
            group=webstack
            state=link
            mode=0775
      sudo: true
      when: not assets_only
    
    - name: sync files to host
      sudo: false
      local_action: >
        command /usr/bin/rsync -az
          --rsync-path="sudo -n rsync"
          -e "ssh -p {{ ansible_port | default(ansible_ssh_port) }}"
          {% if not assets_only %}
          --include='/run.properties'
          --include='/ngx-upstream/comments/upstream.conf'
          --include='/comments-all/target/*jarjar.jar'
          --include='/comments-ts/g/user/UserServices.json'
          {% endif %}
          --include='/comments-ts/dist/**'
          --include='/comments-ts/*.html'
          --include='/comments-ts/favicon.ico'
          --filter='-! */'
          --prune-empty-dirs
          --chown={{target_user}}:webstack
          --chmod=u=rwX,g=rwX,o=rX
          {{project_dir}}/
          deploy@{{inventory_hostname}}:/home/deploy/projects/comments/{{deploy_rev}}
      register: rsync
      changed_when: "'Number of files transferred: 0' not in rsync.stdout"
    
    - name: rpc host
      lineinfile: dest=/home/deploy/projects/comments/{{deploy_rev}}/comments-ts/index.html
                  regexp="^    window.rpc_host"
                  line="{% if rpc_host %}    window.rpc_host = '{{rpc_host}}'{% endif %}"
      sudo: true
    
    - name: nginx domain
      lineinfile: dest=/home/deploy/projects/comments/{{deploy_rev}}/ngx-upstream/comments/upstream.conf
                  regexp="^  server_name comments.local;$"
                  line="  server_name {{ngx_domain}};{% if ngx_certs_dir %} listen 443 ssl http2; ssl_certificate {{ngx_certs_dir}}/cert_chain.crt; ssl_certificate_key {{ngx_certs_dir}}/private.key;{% endif %}"
      sudo: true
      when: not assets_only
    
    - name: link nginx www dir
      file: src=/home/deploy/projects/comments/{{deploy_rev}}/comments-ts
            dest=/home/deploy/projects/comments/{{deploy_rev}}/ngx-upstream/comments/www
            owner={{target_user}}
            group=webstack
            state=link
            mode=0775
      sudo: true
      when: not assets_only
    
    - name: link target dir
      file: src=/home/deploy/projects/comments/target
            dest=/home/deploy/projects/comments/{{deploy_rev}}/target 
            owner={{target_user}}
            group=webstack 
            state=link 
            mode=0775
      sudo: true
      when: not assets_only
    
    - name: link current rev
      file: src=/home/deploy/projects/comments/{{deploy_rev}}
            dest=/home/deploy/projects/comments/current
            owner={{target_user}}
            group=webstack
            state=link
            mode=0775
      sudo: true
    
    - name: link upstream dir
      file: src=/home/deploy/projects/comments/current/ngx-upstream/comments
            dest=/home/deploy/nginx/ngx-upstream/comments
            owner={{target_user}}
            group=webstack
            state=link
            mode=0775
      sudo: true
      when: not assets_only
    
    - name: systemd template
      template: src=systemd/comments.service dest=/etc/systemd/system/comments.service owner=deploy group=deploy
      sudo: true
    
    - name: stop nginx
      command: systemctl stop nginx
      ignore_errors: true
      sudo: true
      when: deploy_type != '0'
    
    - name: restart comments
      command: systemctl restart comments
      ignore_errors: true
      sudo: true
      when: not assets_only and deploy_type != '0'
    
    - name: start nginx
      command: systemctl start nginx
      ignore_errors: true
      sudo: true
      when: deploy_type != '0'

